In [1]:
import pandas as pd
import numpy as np

In [2]:
# EXTRACCIÓN DE DATOS DE LA CARPETA DATA/EDUCACION

In [3]:
GastoEducacionPorcentajePBI = pd.read_csv("./data/Educacion/GastoEducacionPorcentajePBI.csv", delimiter=",")
contruccionInstitucionesPorcentajeGE = pd.read_csv("./data/Educacion/contruccionInstitucionesEducacion.csv", delimiter=",")
gastoInvestigacionPorcentajeGE = pd.read_csv("./data/Educacion/gastoInvestigacion.csv", delimiter=",")
subvencionesPorcentajeGE = pd.read_csv("./data/Educacion/SubvencionEscolar.csv", delimiter=",")
sueldoEmpleadosPorcentajeGE = pd.read_csv("./data/Educacion/sueldoMaestros.csv", delimiter=",")

In [4]:
#PRIMER TRATAMIENTO DE DATOS 
#Se eliminan los valores no deseados y se nos quedamos solo con los valores objetivos

In [5]:
GastoEducacionPorcentajePBI = GastoEducacionPorcentajePBI[['Reference Area','Time Period','Observation Value']]
GastoEducacionPorcentajePBI['pais_key'] = GastoEducacionPorcentajePBI['Reference Area']
GastoEducacionPorcentajePBI.drop('Reference Area', axis=1, inplace=True)
GastoEducacionPorcentajePBI['tiempo_key'] = GastoEducacionPorcentajePBI['Time Period']
GastoEducacionPorcentajePBI.drop('Time Period', axis=1, inplace=True)
GastoEducacionPorcentajePBI['porcentajeGastoEducacion'] = GastoEducacionPorcentajePBI['Observation Value']
GastoEducacionPorcentajePBI.drop('Observation Value', axis=1, inplace=True)
#-------------------------------------------------------------------------------------------------------------------
contruccionInstitucionesPorcentajeGE = contruccionInstitucionesPorcentajeGE[['Reference Area','Time Period','Observation Value']]
contruccionInstitucionesPorcentajeGE['pais_key'] = contruccionInstitucionesPorcentajeGE['Reference Area']
contruccionInstitucionesPorcentajeGE.drop('Reference Area', axis=1, inplace=True)
contruccionInstitucionesPorcentajeGE['tiempo_key'] = contruccionInstitucionesPorcentajeGE['Time Period']
contruccionInstitucionesPorcentajeGE.drop('Time Period', axis=1, inplace=True)
contruccionInstitucionesPorcentajeGE['porcentajeGastoEducacion'] = contruccionInstitucionesPorcentajeGE['Observation Value']
contruccionInstitucionesPorcentajeGE.drop('Observation Value', axis=1, inplace=True)
#-------------------------------------------------------------------------------------------------------------------
gastoInvestigacionPorcentajeGE = gastoInvestigacionPorcentajeGE[['Reference Area','Time Period','Observation Value']]
gastoInvestigacionPorcentajeGE['pais_key'] = gastoInvestigacionPorcentajeGE['Reference Area']
gastoInvestigacionPorcentajeGE.drop('Reference Area', axis=1, inplace=True)
gastoInvestigacionPorcentajeGE['tiempo_key'] = gastoInvestigacionPorcentajeGE['Time Period']
gastoInvestigacionPorcentajeGE.drop('Time Period', axis=1, inplace=True)
gastoInvestigacionPorcentajeGE['porcentajeGastoEducacion'] = gastoInvestigacionPorcentajeGE['Observation Value']
gastoInvestigacionPorcentajeGE.drop('Observation Value', axis=1, inplace=True)
#-------------------------------------------------------------------------------------------------------------------
subvencionesPorcentajeGE = subvencionesPorcentajeGE[['Reference Area','Time Period','Observation Value']]
subvencionesPorcentajeGE['pais_key'] = subvencionesPorcentajeGE['Reference Area']
subvencionesPorcentajeGE.drop('Reference Area', axis=1, inplace=True)
subvencionesPorcentajeGE['tiempo_key'] = subvencionesPorcentajeGE['Time Period']
subvencionesPorcentajeGE.drop('Time Period', axis=1, inplace=True)
subvencionesPorcentajeGE['porcentajeGastoEducacion'] = subvencionesPorcentajeGE['Observation Value']
subvencionesPorcentajeGE.drop('Observation Value', axis=1, inplace=True)
#-------------------------------------------------------------------------------------------------------------------
sueldoEmpleadosPorcentajeGE = sueldoEmpleadosPorcentajeGE[['Reference Area','Time Period','Observation Value']]
sueldoEmpleadosPorcentajeGE['pais_key'] = sueldoEmpleadosPorcentajeGE['Reference Area']
sueldoEmpleadosPorcentajeGE.drop('Reference Area', axis=1, inplace=True)
sueldoEmpleadosPorcentajeGE['tiempo_key'] = sueldoEmpleadosPorcentajeGE['Time Period']
sueldoEmpleadosPorcentajeGE.drop('Time Period', axis=1, inplace=True)
sueldoEmpleadosPorcentajeGE['porcentajeGastoEducacion'] = sueldoEmpleadosPorcentajeGE['Observation Value']
sueldoEmpleadosPorcentajeGE.drop('Observation Value', axis=1, inplace=True)

In [6]:
#CREACIÓN DE LA DIMENSIÓN EDUCACIÓN

In [7]:
educacion_dim = pd.DataFrame({
    'tipo_porcentaje_gasto_educacion': ["Porcentaje de gasto en educacion respecto al PBI",
                              "Gasto en contruccion de instituaciones respecto al gasto en educacion",
                              "Gasto en investigacion respecto al gasto en educacion",
                              "Gasto en subvencion escolar respecto al gasto en educacion",
                              "Gasto en sueldos a personal respecto al gasto en educacion"]
})
educacion_dim.index = educacion_dim.index+1
educacion_dim.index.name="educacion_key"

In [8]:
#ASIGNACIÓN DE LAS CLAVES PRIMARIAS

In [9]:
GastoEducacionPorcentajePBI=GastoEducacionPorcentajePBI.assign(educacion_key=1)
contruccionInstitucionesPorcentajeGE=contruccionInstitucionesPorcentajeGE.assign(educacion_key=2)
gastoInvestigacionPorcentajeGE=gastoInvestigacionPorcentajeGE.assign(educacion_key=3)
subvencionesPorcentajeGE=subvencionesPorcentajeGE.assign(educacion_key=4)
sueldoEmpleadosPorcentajeGE=sueldoEmpleadosPorcentajeGE.assign(educacion_key=5)

In [10]:
#CREACIÓN DE LA DIMENSIÓN TIEMPO

In [11]:
tiempo_dim = GastoEducacionPorcentajePBI.groupby(by= ["tiempo_key"]).mean()
tiempo_dim["agno"]= tiempo_dim.index
tiempo_dim= tiempo_dim.reset_index(drop=True)
tiempo_dim.index=tiempo_dim.index+1
tiempo_dim.index.name="tiempo_key"
tiempo_dim.drop('porcentajeGastoEducacion', axis=1, inplace=True)
tiempo_dim.drop('educacion_key', axis=1, inplace=True)

In [12]:
#CREACIÓN DE LA DIMENSIÓN PAÍS

In [13]:
pais_dim = GastoEducacionPorcentajePBI.groupby(by= ["pais_key"]).mean()
pais_dim["nombrePais"]= pais_dim.index
pais_dim= pais_dim.reset_index(drop=True)
pais_dim.index=pais_dim.index+1
pais_dim.index.name="pais_key"
pais_dim.drop('porcentajeGastoEducacion', axis=1, inplace=True)
pais_dim.drop('tiempo_key', axis=1, inplace=True)
pais_dim.drop('educacion_key', axis=1, inplace=True)

In [14]:
#PRIMERA AGRUPACIÓN DE DATOS
#Añadimos los datos obtenidos de educación y los combinamos hasta obtener una sola tabla la que usaremos luego

In [15]:
gasto_educacion = pd.DataFrame()
gasto_educacion = gasto_educacion.append(GastoEducacionPorcentajePBI)
gasto_educacion = gasto_educacion.append(contruccionInstitucionesPorcentajeGE)
gasto_educacion = gasto_educacion.append(gastoInvestigacionPorcentajeGE)
gasto_educacion = gasto_educacion.append(subvencionesPorcentajeGE)
gasto_educacion = gasto_educacion.append(sueldoEmpleadosPorcentajeGE)

gasto_educacion= gasto_educacion.reset_index(drop=True)
gasto_educacion.drop_duplicates(inplace=True)

agnos = pd.DataFrame()
agnos = agnos.append(tiempo_dim)
agnos['clave'] = agnos.index
clave_valor = agnos.to_numpy().transpose().tolist()
clave_valor
clave = clave_valor[1]
valor = clave_valor[0]

gasto_educacion["tiempo_key"] = gasto_educacion["tiempo_key"].replace(valor,clave)

In [16]:
#MODIFICAMOS LOS VALORES POR SUS CLAVES RESPECTIVAS

In [17]:
paises = pd.DataFrame()
paises = paises.append(pais_dim)

paises['clave'] = paises.index
p_clave_valor = paises.to_numpy().transpose().tolist()

p_clave = p_clave_valor[1]
p_valor = p_clave_valor[0]


gasto_educacion["pais_key"] = gasto_educacion["pais_key"].replace(p_valor,p_clave)

In [18]:
#TRAEMOS LOS DATOS PARA SALUD

In [19]:
gastoSaludPorcentajePBI = pd.read_csv("./data/Salud/porcentajeGastoSaludPBI.csv", delimiter=",")
gastoconstruccionInstitucionesMedicoGS = pd.read_csv("./data/Salud/contruccionInstituciones.csv", delimiter=",")
gastoMateriaMedicoGS = pd.read_csv("./data/Salud/materialMedico.csv", delimiter=",")
gastoSueldoPersonalMedicoGS = pd.read_csv("./data/Salud/gastoSueldoPersonalSalud.csv", delimiter=",")

In [20]:
#CREAMOS SU DIMENSIÓN

In [21]:
salud_dim = pd.DataFrame({
    'tipo_porcentaje_gasto_salud': ["Porcentaje de gasto en salud respecto al PBI",
                              "Gasto en contruccion de instituaciones respecto al gasto en salud",
                              "Gasto en compra material medico respecto al gasto en salud",
                              "Gasto en sueldos al personal respecto al gasto en salud"]
})
salud_dim.index = salud_dim.index+1
salud_dim.index.name="educacion_key"

In [22]:
#ASIGNAMOS SUS CLAVES

In [23]:
gastoSaludPorcentajePBI=gastoSaludPorcentajePBI.assign(salud_key=1)
gastoconstruccionInstitucionesMedicoGS=gastoconstruccionInstitucionesMedicoGS.assign(salud_key=2)
gastoMateriaMedicoGS=gastoMateriaMedicoGS.assign(salud_key=3)
gastoSueldoPersonalMedicoGS=gastoSueldoPersonalMedicoGS.assign(salud_key=4)

In [24]:
#VOLVEMOS A REPETIR EL PROCESO DE AGRUPAR LOS DATOS, EN ESTE CASO CON LOS DATOS DE SALUD

In [25]:
gastoSalud = pd.DataFrame()
gastoSalud = gastoSalud.append(gastoSaludPorcentajePBI)
gastoSalud = gastoSalud.append(gastoconstruccionInstitucionesMedicoGS)
gastoSalud = gastoSalud.append(gastoMateriaMedicoGS)
gastoSalud = gastoSalud.append(gastoSueldoPersonalMedicoGS)

gastoSalud= gastoSalud.reset_index(drop=True)
gastoSalud.drop_duplicates(inplace=True)

gastoSalud["tiempo_key"] = gastoSalud["tiempo_key"].replace(valor,clave)
gastoSalud["pais_key"] = gastoSalud["pais_key"].replace(p_valor,p_clave)

In [26]:
#REALIZAMOS NUESTRO PRIMER JOIN
#repetiremos este proceso con ciertas variaciones que dependen de los datos que vamos a utilizar

In [27]:
educacion_salud = pd.merge(gasto_educacion, gastoSalud, how="outer", on=["pais_key", "tiempo_key"])

educacion_salud.head(10)

,pais_key,tiempo_key,porcentajeGastoEducacion,educacion_key,porcentajeGastoSalud,salud_key
0,1,40,4.80435,1.0,NaN,NaN
1,1,40,18.39787,3.0,NaN,NaN
2,1,39,4.54436,1.0,NaN,NaN
3,1,39,18.46120,3.0,NaN,NaN
4,1,38,3.12562,1.0,8.7,1.0
5,1,38,3.12562,1.0,7.1,2.0
6,1,38,12.82317,3.0,8.7,1.0
7,1,38,12.82317,3.0,7.1,2.0
8,1,37,4.08791,1.0,8.5,1.0
9,1,37,4.08791,1.0,3.5,2.0

In [28]:
#for index, row in gastoSalud.iterrows():     
 #   factoresDesarrollo_fact.loc[(factoresDesarrollo_fact['tiempo_key']==row["tiempo_key"]) & (factoresDesarrollo_fact['pais_key']==row["pais_key"]),['porcentajeGastoSalud','salud_key']]=[row["porcentajeGastoSalud"],row["salud_key"]]

In [29]:
#TENEMOS UNA TABLA CON UNA DISTRIBUCIÓN DE DATOS DIFERENTE, A LA QUE TENEMOS QUE MODIFICAR PARA HACERLA CONGRUENTE 
#LOS DATOS OBTENIDOS CON ANTERIORIDAD

In [30]:
bajoUmbralPobreza = pd.read_csv("./data/pobreza/debajoTresDolares.csv", delimiter=",")
umbralPobreza = pd.DataFrame()
bajoUmbralPobreza['pais_key']= bajoUmbralPobreza['pais_key'].str.strip()

agnos = [1991,1995,2000,2005,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
    
for x in agnos:    
    bajoUmbralPobreza_x = bajoUmbralPobreza[['pais_key', str(x)]]
    bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
    bajoUmbralPobreza_x.drop(str(x), axis=1, inplace=True)
    bajoUmbralPobreza_x=bajoUmbralPobreza_x.assign(tiempo_key=x)
    print(bajoUmbralPobreza_x)
    umbralPobreza = umbralPobreza.append(bajoUmbralPobreza_x)

<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              86.0        1991
1                               Albania              15.5        1991
2                               Algeria              21.5        1991
3                                Angola              54.2        1991
4                             Argentina               1.3        1991
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              18.4        1991
130                            Viet Nam              83.0        1991
131                               Yemen              27.8        1991
132                              Zambia              66.0        1991
133                            Zimbabwe              49.3        1991

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              90.2        1995
1                               Albania               9.4        1995
2                               Algeria              15.4        1995
3                                Angola              55.5        1995
4                             Argentina               3.8        1995
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              17.5        1995
130                            Viet Nam              80.5        1995
131                               Yemen              25.7        1995
132                              Zambia              65.3        1995
133                            Zimbabwe              41.9        1995

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              91.9        2000
1                               Albania               9.4        2000
2                               Algeria               6.6        2000
3                                Angola              51.2        2000
4                             Argentina               7.7        2000
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              19.4        2000
130                            Viet Nam              74.8        2000
131                               Yemen              21.4        2000
132                              Zambia              68.3        2000
133                            Zimbabwe              32.8        2000

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              89.5        2005
1                               Albania               4.7        2005
2                               Algeria               2.5        2005
3                                Angola              47.4        2005
4                             Argentina               5.1        2005
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              23.6        2005
130                            Viet Nam              55.2        2005
131                               Yemen              30.4        2005
132                              Zambia              72.4        2005
133                            Zimbabwe              38.5        2005

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              82.6        2010
1                               Albania               1.6        2010
2                               Algeria               1.3        2010
3                                Angola              50.9        2010
4                             Argentina               1.6        2010
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              10.6        2010
130                            Viet Nam              19.5        2010
131                               Yemen              27.9        2010
132                              Zambia              76.8        2010
133                            Zimbabwe              43.1        2010

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              81.1        2011
1                               Albania               2.0        2011
2                               Algeria               1.2        2011
3                                Angola              54.7        2011
4                             Argentina               0.7        2011
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              10.1        2011
130                            Viet Nam              17.6        2011
131                               Yemen              34.1        2011
132                              Zambia              75.6        2011
133                            Zimbabwe              43.6        2011

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              78.4        2012
1                               Albania               2.3        2012
2                               Algeria               1.2        2012
3                                Angola              54.4        2012
4                             Argentina               0.8        2012
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)               9.6        2012
130                            Viet Nam              15.3        2012
131                               Yemen              36.7        2012
132                              Zambia              73.4        2012
133                            Zimbabwe              44.1        2012

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              76.4        2013
1                               Albania               1.7        2013
2                               Algeria               1.2        2013
3                                Angola              53.9        2013
4                             Argentina               0.7        2013
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)               9.6        2013
130                            Viet Nam              14.3        2013
131                               Yemen              39.0        2013
132                              Zambia              72.2        2013
133                            Zimbabwe              44.7        2013

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              74.6        2014
1                               Albania               1.4        2014
2                               Algeria               1.1        2014
3                                Angola              53.5        2014
4                             Argentina               0.8        2014
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              10.2        2014
130                            Viet Nam              13.1        2014
131                               Yemen              43.3        2014
132                              Zambia              71.4        2014
133                            Zimbabwe              45.0        2014

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              72.9        2015
1                               Albania               1.3        2015
2                               Algeria               1.1        2015
3                                Angola              53.3        2015
4                             Argentina               0.7        2015
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              11.2        2015
130                            Viet Nam              11.3        2015
131                               Yemen              66.8        2015
132                              Zambia              71.1        2015
133                            Zimbabwe              45.2        2015

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              71.3        2016
1                               Albania               1.2        2016
2                               Algeria               1.2        2016
3                                Angola              53.6        2016
4                             Argentina               0.7        2016
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              13.3        2016
130                            Viet Nam               9.6        2016
131                               Yemen              80.3        2016
132                              Zambia              69.0        2016
133                            Zimbabwe              45.3        2016

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              69.3        2017
1                               Albania               1.0        2017
2                               Algeria               1.2        2017
3                                Angola              53.7        2017
4                             Argentina               0.7        2017
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              15.6        2017
130                            Viet Nam               8.2        2017
131                               Yemen              84.1        2017
132                              Zambia              67.0        2017
133                            Zimbabwe              44.7        2017

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              67.9        2018
1                               Albania               0.9        2018
2                               Algeria               1.2        2018
3                                Angola              53.6        2018
4                             Argentina               0.7        2018
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              17.7        2018
130                            Viet Nam               7.1        2018
131                               Yemen              84.7        2018
132                              Zambia              65.3        2018
133                            Zimbabwe              43.5        2018

[134 rows x 3 columns]
                               pais_key  indicadorPobreza  tiempo_key
0                           Afghanistan              66.3        2019
1                               Albania               0.8        2019
2                               Algeria               1.3        2019
3                                Angola              53.3        2019
4                             Argentina               0.7        2019
..                                  ...               ...         ...
129  Venezuela (Bolivarian Republic of)              18.8        2019
130                            Viet Nam               6.2        2019
131                               Yemen              85.1        2019
132                              Zambia              64.0        2019
133                            Zimbabwe              43.1        2019

[134 rows x 3 columns]

<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-30-9843a7fb9ca4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bajoUmbralPobreza_x['indicadorPobreza'] = bajoUmbralPobreza_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [31]:
accesoAguaPotable = pd.read_csv("./data/pobreza/PorcentajePersonasAccesoAguaPotable.csv", delimiter=",")


agua_index=accesoAguaPotable[accesoAguaPotable['RESIDENCE AREA']!='Total'].index
accesoAguaPotable=accesoAguaPotable.drop(agua_index)
accesoAguaPotable.drop('RESIDENCE AREA', axis=1, inplace=True)

In [32]:

pobreza_dim = pd.DataFrame({
    'indicador_pobreza': ["vive por debajo del umbral de pobreza",
                              "no cuenta con acceso a agua potable"]
})

pobreza_dim.index = pobreza_dim.index+1
pobreza_dim.index.name="educacion_key"
pobreza_dim

umbralPobreza=umbralPobreza.assign(pobreza_key=1)
accesoAguaPotable=accesoAguaPotable.assign(pobreza_key=2)

pobreza = pd.DataFrame()
pobreza = pobreza.append(umbralPobreza)
pobreza = pobreza.append(accesoAguaPotable)

pobreza= pobreza.reset_index(drop=True)
pobreza.drop_duplicates(inplace=True)

pobreza["tiempo_key"] = pobreza["tiempo_key"].replace(valor,clave)
pobreza["pais_key"] = pobreza["pais_key"].replace(p_valor,p_clave)

In [ ]:
#REALIZAMOS NUESTRO TERCER JOIN CON AÑADIDURA DE LOS DATOS DE POBREZA

In [35]:
educacion_salud_pobreza = pd.merge(educacion_salud, pobreza, how="outer", on=["pais_key", "tiempo_key"])
educacion_salud_pobreza

,pais_key,tiempo_key,porcentajeGastoEducacion,educacion_key,porcentajeGastoSalud,salud_key,indicadorPobreza,pobreza_key
0,1,40,4.80435,1.0,NaN,NaN,67.9,1.0
1,1,40,18.39787,3.0,NaN,NaN,67.9,1.0
2,1,39,4.54436,1.0,NaN,NaN,69.3,1.0
3,1,39,18.46120,3.0,NaN,NaN,69.3,1.0
4,1,38,3.12562,1.0,8.7,1.0,71.3,1.0
...,...,...,...,...,...,...,...,...
33857,194,16,NaN,NaN,NaN,NaN,61.0,2.0
33858,195,16,NaN,NaN,NaN,NaN,66.0,2.0
33859,196,16,NaN,NaN,NaN,NaN,49.0,2.0
33860,197,31,NaN,NaN,NaN,NaN,80.0,2.0
33861,197,26,NaN,NaN,NaN,NaN,80.0,2.0

In [36]:
edadMedia = pd.read_csv("./data/demografia/edadMedia.csv", delimiter=",")

edadMedia['pais_key'] = edadMedia['pais_key'].str.strip()
edadMedia["pais_key"] = edadMedia["pais_key"].replace(p_valor,p_clave)

agnos = [1990,1995,2000,2005,2010,2015,2019]
indicadorEdadMedia = pd.DataFrame()
for x in agnos:    
    edadMedia_x = edadMedia[['pais_key', str(x)]]
    edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
    edadMedia_x.drop(str(x), axis=1, inplace=True)
    edadMedia_x=edadMedia_x.assign(tiempo_key=x)
    print(edadMedia_x)
    indicadorEdadMedia = indicadorEdadMedia.append(edadMedia_x)

    pais_key  indicadorDemografico  tiempo_key
0          1                  15.8        1990
1          2                  24.0        1990
2          3                  18.0        1990
3          5                  16.1        1990
4          7                  25.2        1990
..       ...                   ...         ...
180      193                  20.9        1990
181      194                  21.1        1990
182      195                  14.4        1990
183      196                  16.2        1990
184      197                  16.9        1990

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  16.0        1995
1          2                  24.6        1995
2          3                  19.4        1995
3          5                  16.1        1995
4          7                  26.5        1995
..       ...                   ...         ...
180      193                  22.0        1995
181      194                  22.3        1995
182      195                  14.9        1995
183      196                  16.4        1995
184      197                  17.6        1995

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  15.5        2000
1          2                  27.0        2000
2          3                  21.7        2000
3          5                  16.3        2000
4          7                  28.1        2000
..       ...                   ...         ...
180      193                  23.2        2000
181      194                  24.2        2000
182      195                  15.5        2000
183      196                  16.6        2000
184      197                  18.2        2000

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  16.0        2005
1          2                  29.1        2005
2          3                  24.1        2005
3          5                  16.4        2005
4          7                  29.5        2005
..       ...                   ...         ...
180      193                  24.5        2005
181      194                  26.4        2005
182      195                  16.6        2005
183      196                  16.3        2005
184      197                  18.3        2005

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  15.9        2010
1          2                  32.2        2010
2          3                  26.0        2010
3          5                  16.4        2010
4          7                  31.1        2010
..       ...                   ...         ...
180      193                  25.8        2010
181      194                  28.5        2010
182      195                  17.9        2010
183      196                  16.2        2010
184      197                  18.6        2010

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  17.2        2015
1          2                  34.9        2015
2          3                  27.5        2015
3          5                  16.4        2015
4          7                  32.6        2015
..       ...                   ...         ...
180      193                  27.3        2015
181      194                  30.5        2015
182      195                  19.1        2015
183      196                  16.7        2015
184      197                  18.4        2015

[185 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                  18.4        2019
1          2                  36.4        2019
2          3                  28.5        2019
3          5                  16.7        2019
4          7                  34.0        2019
..       ...                   ...         ...
180      193                  29.6        2019
181      194                  32.5        2019
182      195                  20.2        2019
183      196                  17.6        2019
184      197                  18.7        2019

[185 rows x 3 columns]

<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-968843f01f86>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edadMedia_x['indicadorDemografico'] = edadMedia_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [37]:
demografia_dim = pd.DataFrame({
    'indicador_pobreza': ["edad media",
                              "indice de desigualdad"]
})

demografia_dim.index = demografia_dim.index+1
demografia_dim.index.name="demografia_key"
indicadorEdadMedia=indicadorEdadMedia.assign(demografia_key=1)

In [46]:
indiceDesigualdad = pd.read_csv("./data/demografia/IndiceDesigualdad.csv", delimiter=",")
indiceDesigualdad['pais_key'] = indiceDesigualdad['pais_key'].str.strip()
indiceDesigualdad["pais_key"] = indiceDesigualdad["pais_key"].replace(p_valor,p_clave)





agnos = [1995,2000,2005,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
indicadorDesigualdad = pd.DataFrame()
for x in agnos:    
    desigualdad_x = indiceDesigualdad[['pais_key', str(x)]]
    desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
    desigualdad_x.drop(str(x), axis=1, inplace=True)
    desigualdad_x=desigualdad_x.assign(tiempo_key=x)
    print(desigualdad_x)
    indicadorDesigualdad = indicadorDesigualdad.append(desigualdad_x)

indicadorDesigualdad=indicadorDesigualdad.assign(demografia_key=2)

    pais_key indicadorDemografico  tiempo_key
0          1                   ..        1995
1          2                   ..        1995
2          3                0.682        1995
3          5                   ..        1995
4          8                0.427        1995
..       ...                  ...         ...
157      193                0.555        1995
158      194                0.367        1995
159      195                   ..        1995
160      196                0.647        1995
161      197                0.596        1995

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                   ..        2000
1          2                0.334        2000
2          3                0.624        2000
3          5                   ..        2000
4          8                0.417        2000
..       ...                  ...         ...
157      193                   ..        2000
158      194                0.333        2000
159      195                0.807        2000
160      196                0.652        2000
161      197                0.626        2000

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.745        2005
1          2                0.306        2005
2          3                0.552        2005
3          5                   ..        2005
4          8                0.372        2005
..       ...                  ...         ...
157      193                0.488        2005
158      194                0.308        2005
159      195                0.796        2005
160      196                0.627        2005
161      197                0.593        2005

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.751        2010
1          2                0.242        2010
2          3                0.507        2010
3          5                   ..        2010
4          8                0.358        2010
..       ...                  ...         ...
157      193                0.487        2010
158      194                0.308        2010
159      195                0.799        2010
160      196                0.596        2010
161      197                0.595        2010

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.743        2011
1          2                0.249        2011
2          3                  0.5        2011
3          5                   ..        2011
4          8                0.354        2011
..       ...                  ...         ...
157      193                0.486        2011
158      194                0.314        2011
159      195                  0.8        2011
160      196                0.599        2011
161      197                 0.59        2011

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.734        2012
1          2                 0.23        2012
2          3                0.419        2012
3          5                   ..        2012
4          8                0.351        2012
..       ...                  ...         ...
157      193                0.485        2012
158      194                0.313        2012
159      195                0.803        2012
160      196                0.594        2012
161      197                0.587        2012

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.724        2013
1          2                0.221        2013
2          3                0.416        2013
3          5                   ..        2013
4          8                0.348        2013
..       ...                  ...         ...
157      193                0.483        2013
158      194                0.315        2013
159      195                0.805        2013
160      196                0.589        2013
161      197                0.551        2013

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.714        2014
1          2                0.217        2014
2          3                0.424        2014
3          5                0.537        2014
4          8                0.345        2014
..       ...                  ...         ...
157      193                0.482        2014
158      194                0.316        2014
159      195                0.809        2014
160      196                0.587        2014
161      197                0.548        2014

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.702        2015
1          2                0.207        2015
2          3                0.427        2015
3          5                0.534        2015
4          8                   ..        2015
..       ...                  ...         ...
157      193                0.483        2015
158      194                0.319        2015
159      195                0.819        2015
160      196                0.573        2015
161      197                0.546        2015

[162 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                 0.690        2016
1          2                 0.205        2016
2          3                 0.425        2016
3          5                 0.531        2016
4          8                 0.338        2016
..       ...                   ...         ...
157      193                 0.498        2016
158      194                 0.308        2016
159      195                 0.814        2016
160      196                 0.548        2016
161      197                 0.541        2016

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                0.673        2017
1          2                0.187        2017
2          3                0.434        2017
3          5                0.539        2017
4          8                0.332        2017
..       ...                  ...         ...
157      193                0.478        2017
158      194                0.302        2017
159      195                0.813        2017
160      196                0.542        2017
161      197                0.533        2017

[162 rows x 3 columns]
    pais_key indicadorDemografico  tiempo_key
0          1                   ..        2018
1          2                0.186        2018
2          3                0.433        2018
3          5                0.537        2018
4          8                0.328        2018
..       ...                  ...         ...
157      193                0.479        2018
158      194                0.299        2018
159      195                0.811        2018
160      196                0.539        2018
161      197                0.532        2018

[162 rows x 3 columns]
    pais_key  indicadorDemografico  tiempo_key
0          1                 0.655        2019
1          2                 0.181        2019
2          3                 0.429        2019
3          5                 0.536        2019
4          8                 0.328        2019
..       ...                   ...         ...
157      193                 0.479        2019
158      194                 0.296        2019
159      195                 0.795        2019
160      196                 0.539        2019
161      197                 0.527        2019

[162 rows x 3 columns]

<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-46-d7e1d7ee2f33>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desigualdad_x['indicadorDemografico'] = desigualdad_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [47]:
demografia = pd.DataFrame()
demografia = demografia.append(indicadorEdadMedia)
demografia = demografia.append(indicadorDesigualdad)

demografia['tiempo_key'] = demografia['tiempo_key'].replace(valor, clave)

In [48]:
#EN NUESTRO CUARTO JOIN AÑADIMOS LOS DATOS DE DEMOGRAFÍA

In [49]:
educacion_salud_pobreza_demo = pd.merge(educacion_salud_pobreza, demografia, how="outer", on=["pais_key", "tiempo_key"])
educacion_salud_pobreza_demo

,pais_key,tiempo_key,porcentajeGastoEducacion,educacion_key,porcentajeGastoSalud,salud_key,indicadorPobreza,pobreza_key,indicadorDemografico,demografia_key
0,1,40,4.80435,1.0,NaN,NaN,67.9,1.0,..,2.0
1,1,40,18.39787,3.0,NaN,NaN,67.9,1.0,..,2.0
2,1,39,4.54436,1.0,NaN,NaN,69.3,1.0,0.673,2.0
3,1,39,18.46120,3.0,NaN,NaN,69.3,1.0,0.673,2.0
4,1,38,3.12562,1.0,8.7,1.0,71.3,1.0,0.69,2.0
...,...,...,...,...,...,...,...,...,...,...
39751,170,40,NaN,NaN,NaN,NaN,NaN,NaN,0.041,2.0
39752,171,40,NaN,NaN,NaN,NaN,NaN,NaN,0.039,2.0
39753,178,40,NaN,NaN,NaN,NaN,NaN,NaN,0.357,2.0
39754,United Kingdom,40,NaN,NaN,NaN,NaN,NaN,NaN,0.124,2.0
39755,United States,40,NaN,NaN,NaN,NaN,NaN,NaN,0.211,2.0

In [50]:
idh = pd.read_csv("./data/idh/indiceDesarrolloHumano.csv", delimiter=",")
idh['pais_key'] = idh['pais_key'].str.strip()

idh["pais_key"] = idh["pais_key"].replace(p_valor,p_clave)


agnos = [1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
indiceDesarrolloHumano = pd.DataFrame()
for x in agnos:    
    idh_x = idh[['pais_key', str(x)]]
    idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
    idh_x.drop(str(x), axis=1, inplace=True)
    idh_x=idh_x.assign(tiempo_key=x)
    print(idh_x)
    indiceDesarrolloHumano = indiceDesarrolloHumano.append(idh_x)

indiceDesarrolloHumano = indiceDesarrolloHumano

<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.302        1990
1          2                      0.65        1990
2          3                     0.572        1990
3          5                        ..        1990
4          7                        ..        1990
..       ...                       ...         ...
183      193                     0.644        1990
184      194                     0.483        1990
185      195                     0.401        1990
186      196                     0.421        1990
187      197                     0.478        1990

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.307        1991
1          2                     0.631        1991
2          3                     0.576        1991
3          5                        ..        1991
4          7                        ..        1991
..       ...                       ...         ...
183      193                     0.654        1991
184      194                     0.493        1991
185      195                     0.401        1991
186      196                     0.417        1991
187      197                     0.481        1991

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.316        1992
1          2                     0.615        1992
2          3                     0.582        1992
3          5                        ..        1992
4          7                        ..        1992
..       ...                       ...         ...
183      193                      0.66        1992
184      194                     0.504        1992
185      195                     0.404        1992
186      196                     0.416        1992
187      197                     0.467        1992

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.312        1993
1          2                     0.618        1993
2          3                     0.586        1993
3          5                        ..        1993
4          7                        ..        1993
..       ...                       ...         ...
183      193                     0.662        1993
184      194                     0.514        1993
185      195                     0.406        1993
186      196                     0.419        1993
187      197                     0.463        1993

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.307        1994
1          2                     0.624        1994
2          3                      0.59        1994
3          5                        ..        1994
4          7                        ..        1994
..       ...                       ...         ...
183      193                     0.662        1994
184      194                     0.525        1994
185      195                     0.408        1994
186      196                     0.414        1994
187      197                      0.46        1994

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.331        1995
1          2                     0.637        1995
2          3                     0.595        1995
3          5                        ..        1995
4          7                        ..        1995
..       ...                       ...         ...
183      193                     0.666        1995
184      194                     0.537        1995
185      195                     0.414        1995
186      196                     0.415        1995
187      197                     0.453        1995

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.335        1996
1          2                     0.646        1996
2          3                     0.602        1996
3          5                        ..        1996
4          7                        ..        1996
..       ...                       ...         ...
183      193                     0.668        1996
184      194                     0.548        1996
185      195                     0.421        1996
186      196                     0.416        1996
187      197                     0.453        1996

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.339        1997
1          2                     0.645        1997
2          3                     0.611        1997
3          5                        ..        1997
4          7                        ..        1997
..       ...                       ...         ...
183      193                      0.67        1997
184      194                     0.547        1997
185      195                     0.426        1997
186      196                     0.416        1997
187      197                     0.447        1997

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.344        1998
1          2                     0.655        1998
2          3                     0.621        1998
3          5                        ..        1998
4          7                        ..        1998
..       ...                       ...         ...
183      193                     0.672        1998
184      194                     0.567        1998
185      195                     0.431        1998
186      196                     0.416        1998
187      197                     0.442        1998

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.348        1999
1          2                     0.665        1999
2          3                     0.629        1999
3          5                     0.391        1999
4          7                        ..        1999
..       ...                       ...         ...
183      193                     0.674        1999
184      194                     0.574        1999
185      195                     0.435        1999
186      196                      0.42        1999
187      197                     0.437        1999

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                      0.35        2000
1          2                     0.671        2000
2          3                     0.637        2000
3          5                       0.4        2000
4          7                        ..        2000
..       ...                       ...         ...
183      193                     0.676        2000
184      194                     0.586        2000
185      195                     0.444        2000
186      196                     0.425        2000
187      197                      0.43        2000

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.353        2001
1          2                     0.678        2001
2          3                     0.647        2001
3          5                      0.41        2001
4          7                        ..        2001
..       ...                       ...         ...
183      193                     0.684        2001
184      194                     0.594        2001
185      195                     0.453        2001
186      196                     0.432        2001
187      197                     0.431        2001

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.384        2002
1          2                     0.684        2002
2          3                     0.657        2002
3          5                     0.426        2002
4          7                        ..        2002
..       ...                       ...         ...
183      193                     0.692        2002
184      194                     0.602        2002
185      195                     0.461        2002
186      196                     0.441        2002
187      197                     0.423        2002

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.393        2003
1          2                     0.691        2003
2          3                     0.667        2003
3          5                     0.435        2003
4          7                        ..        2003
..       ...                       ...         ...
183      193                     0.692        2003
184      194                     0.611        2003
185      195                      0.47        2003
186      196                     0.451        2003
187      197                     0.414        2003

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.409        2004
1          2                     0.696        2004
2          3                     0.677        2004
3          5                     0.446        2004
4          7                        ..        2004
..       ...                       ...         ...
183      193                     0.704        2004
184      194                      0.62        2004
185      195                     0.477        2004
186      196                      0.46        2004
187      197                     0.411        2004

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.418        2005
1          2                     0.706        2005
2          3                     0.685        2005
3          5                      0.46        2005
4          7                     0.764        2005
..       ...                       ...         ...
183      193                     0.718        2005
184      194                     0.624        2005
185      195                     0.483        2005
186      196                     0.471        2005
187      197                     0.411        2005

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.429        2006
1          2                     0.713        2006
2          3                      0.69        2006
3          5                     0.473        2006
4          7                     0.771        2006
..       ...                       ...         ...
183      193                     0.731        2006
184      194                     0.632        2006
185      195                     0.488        2006
186      196                     0.482        2006
187      197                     0.414        2006

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.447        2007
1          2                     0.722        2007
2          3                       0.7        2007
3          5                     0.489        2007
4          7                     0.776        2007
..       ...                       ...         ...
183      193                     0.748        2007
184      194                      0.64        2007
185      195                     0.492        2007
186      196                     0.488        2007
187      197                     0.421        2007

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.447        2008
1          2                     0.728        2008
2          3                     0.702        2008
3          5                     0.501        2008
4          7                     0.774        2008
..       ...                       ...         ...
183      193                     0.757        2008
184      194                     0.647        2008
185      195                     0.495        2008
186      196                     0.503        2008
187      197                     0.422        2008

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                      0.46        2009
1          2                     0.733        2009
2          3                     0.711        2009
3          5                     0.515        2009
4          7                     0.767        2009
..       ...                       ...         ...
183      193                     0.756        2009
184      194                     0.659        2009
185      195                     0.502        2009
186      196                     0.517        2009
187      197                     0.458        2009

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.472        2010
1          2                     0.745        2010
2          3                     0.721        2010
3          5                     0.517        2010
4          7                     0.763        2010
..       ...                       ...         ...
183      193                     0.757        2010
184      194                     0.661        2010
185      195                     0.506        2010
186      196                     0.527        2010
187      197                     0.482        2010

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.477        2011
1          2                     0.764        2011
2          3                     0.728        2011
3          5                     0.533        2011
4          7                     0.755        2011
..       ...                       ...         ...
183      193                     0.769        2011
184      194                     0.671        2011
185      195                     0.506        2011
186      196                     0.534        2011
187      197                     0.499        2011

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.489        2012
1          2                     0.775        2012
2          3                     0.728        2012
3          5                     0.544        2012
4          7                     0.759        2012
..       ...                       ...         ...
183      193                     0.772        2012
184      194                     0.676        2012
185      195                     0.504        2012
186      196                     0.549        2012
187      197                     0.525        2012

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.496        2013
1          2                     0.782        2013
2          3                     0.729        2013
3          5                     0.555        2013
4          7                      0.76        2013
..       ...                       ...         ...
183      193                     0.777        2013
184      194                     0.681        2013
185      195                     0.509        2013
186      196                     0.557        2013
187      197                     0.537        2013

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                       0.5        2014
1          2                     0.787        2014
2          3                     0.736        2014
3          5                     0.565        2014
4          7                      0.76        2014
..       ...                       ...         ...
183      193                     0.775        2014
184      194                     0.683        2014
185      195                     0.502        2014
186      196                     0.561        2014
187      197                     0.547        2014

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                       0.5        2015
1          2                     0.788        2015
2          3                      0.74        2015
3          5                     0.572        2015
4          7                     0.762        2015
..       ...                       ...         ...
183      193                     0.769        2015
184      194                     0.688        2015
185      195                     0.483        2015
186      196                     0.569        2015
187      197                     0.553        2015

[188 rows x 3 columns]
    pais_key indicadorDesarrolloHumano  tiempo_key
0          1                     0.502        2016
1          2                     0.788        2016
2          3                     0.743        2016
3          5                     0.578        2016
4          7                     0.765        2016
..       ...                       ...         ...
183      193                     0.759        2016
184      194                     0.693        2016
185      195                     0.474        2016
186      196                     0.571        2016
187      197                     0.558        2016

[188 rows x 3 columns]

    pais_key  indicadorDesarrolloHumano  tiempo_key
0          1                      0.506        2017
1          2                      0.790        2017
2          3                      0.745        2017
3          5                      0.582        2017
4          7                      0.768        2017
..       ...                        ...         ...
183      193                      0.743        2017
184      194                      0.696        2017
185      195                      0.467        2017
186      196                      0.578        2017
187      197                      0.563        2017

[188 rows x 3 columns]
    pais_key  indicadorDesarrolloHumano  tiempo_key
0          1                      0.509        2018
1          2                      0.792        2018
2          3                      0.746        2018
3          5                      0.582        2018
4          7                      0.772        2018
..       ...                        ...         ...
183      193                      0.733        2018
184      194                      0.700        2018
185      195                      0.468        2018
186      196                      0.582        2018
187      197                      0.569        2018

[188 rows x 3 columns]
    pais_key  indicadorDesarrolloHumano  tiempo_key
0          1                      0.511        2019
1          2                      0.795        2019
2          3                      0.748        2019
3          5                      0.581        2019
4          7                      0.778        2019
..       ...                        ...         ...
183      193                      0.711        2019
184      194                      0.704        2019
185      195                      0.470        2019
186      196                      0.584        2019
187      197                      0.571        2019

[188 rows x 3 columns]

<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-50-0dcd76fd3442>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  idh_x['indicadorDesarrolloHumano'] = idh_x[str(x)]
/home/tryopx80p/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [51]:
indiceDesarrolloHumano["tiempo_key"] = indiceDesarrolloHumano["tiempo_key"].replace(valor,clave)

In [52]:
#NUESTRO ÚLTIMO JOIN LO REALIZAMOS AÑADIENDO LOS DATOS DEL ÍNDICE DE DESARROLLO HUMANO

In [56]:
factoresDesarrollo_fact = pd.merge(educacion_salud_pobreza_demo, indiceDesarrolloHumano, how="outer", on=["pais_key", "tiempo_key"])
factoresDesarrollo_fact

,pais_key,tiempo_key,porcentajeGastoEducacion,educacion_key,porcentajeGastoSalud,salud_key,indicadorPobreza,pobreza_key,indicadorDemografico,demografia_key,indicadorDesarrolloHumano
0,1,40,4.80435,1.0,NaN,NaN,67.9,1.0,..,2.0,0.509
1,1,40,18.39787,3.0,NaN,NaN,67.9,1.0,..,2.0,0.509
2,1,39,4.54436,1.0,NaN,NaN,69.3,1.0,0.673,2.0,0.506
3,1,39,18.46120,3.0,NaN,NaN,69.3,1.0,0.673,2.0,0.506
4,1,38,3.12562,1.0,8.7,1.0,71.3,1.0,0.69,2.0,0.502
...,...,...,...,...,...,...,...,...,...,...,...
40674,53,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.742
40675,103,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.919
40676,113,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.704
40677,135,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.826
40678,149,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.779

In [ ]:
#EL PASO FINAL SERÁ ELIMINAR TODOS LOS VALORES QUE CONTANGAN NULOS

In [59]:
factoresDesarrollo_fact = factoresDesarrollo_fact.dropna()
factoresDesarrollo_fact

,pais_key,tiempo_key,porcentajeGastoEducacion,educacion_key,porcentajeGastoSalud,salud_key,indicadorPobreza,pobreza_key,indicadorDemografico,demografia_key,indicadorDesarrolloHumano
4,1,38,3.12562,1.0,8.7,1.0,71.3,1.0,0.69,2.0,0.502
5,1,38,3.12562,1.0,8.7,1.0,64.0,2.0,0.69,2.0,0.502
6,1,38,3.12562,1.0,7.1,2.0,71.3,1.0,0.69,2.0,0.502
7,1,38,3.12562,1.0,7.1,2.0,64.0,2.0,0.69,2.0,0.502
8,1,38,12.82317,3.0,8.7,1.0,71.3,1.0,0.69,2.0,0.502
...,...,...,...,...,...,...,...,...,...,...,...
32759,16,36,12.90402,4.0,3.7,1.0,83.0,2.0,0.57,2.0,0.579
32760,16,36,12.90402,4.0,8.9,2.0,50.6,1.0,0.57,2.0,0.579
32761,16,36,12.90402,4.0,8.9,2.0,83.0,2.0,0.57,2.0,0.579
32762,16,36,12.90402,4.0,22.3,3.0,50.6,1.0,0.57,2.0,0.579
32763,16,36,12.90402,4.0,22.3,3.0,83.0,2.0,0.57,2.0,0.579

In [60]:
############################################################
#### FINALMENTE EXPORTAMOS NUESTROS DATOS EN FORMATO CSV ###
############################################################

factoresDesarrollo_fact.to_csv("./producto/factoresDesarrollo_fact.csv")
pais_dim.to_csv("./producto/pais_dim.csv")
tiempo_dim.to_csv("./producto/tiempo_dim.csv")
demografia_dim.to_csv("./producto/demografia_dim.csv")
educacion_dim.to_csv("./producto/educacion_dim.csv")
salud_dim.to_csv("./producto/salud_dim.csv")

NameError: name 'X' is not defined